parameters:
    chang_page_context_admin:
        site:
            url: /
            name: Chang SE
            logo: /build/img/logo-php.png
            logo_square: /build/img/logo-square.png
        menus:
            quick:
                profile:
                    label: chang.ui.profile
                    route: cse_account_profile_update
                    icon: :account_box
                account:
                    label: chang.ui.account
                    route: cse_account_account_update
                    icon: fas fa-shield-alt
                change_password:
                    label: password
                    route: cse_account_change_password
                    icon: sl-ico-social-github
                xchange_password:
                    label: password
                    route: cse_account_change_password
                    icon: sl-ico-social-github
                xaccount:
                    label: chang.ui.account
                    route: cse_account_account_update
                    icon: fas fa-shield-alt
                xprofile:
                    label: chang.ui.profile
                    route: cse_account_profile_update
                    icon: :account_box
            account:
                profile:
                    label: chang.ui.profile
                    route: cse_account_profile_update
                    icon: far fa-user
                account:
                    label: chang.ui.account
                    route: cse_account_account_update
                    icon: fas fa-shield-alt
                change_password:
                    label: chang.ui.change_password
                    route: cse_account_change_password
                    icon: fas fa-key
