chang:
    driver: doctrine/orm
    packages:
        Messenger: true
        Context: true
#        Currency:
#            money:
#                options:
#                    divisor: 100
#                    base_currency: THB
        DataFixture: true
        DoctrineExtension:
            mysql: true
        Exception:
            redirect: true
        ExpressionLanguage: true
        Form:
            convertRaw: true
            generic: true
        Grid: true
        Locale: true
        Menu: true
        Paginate: true
        Security:
            full:
                options:
                    password_strength:
                        algorithm: basic
                    reserved_word:
                        enabled: true
                        words:
                            - chang
                            - dos
#        SequenceNumber: true
        Twig: true
        User: true
        Admin: true
        Web: true
#        Verification:
#            phoneNumber:
#                options:
#                    target_url: /account/verify-number
#                    ignored_request:
#                        - { path: '^(?!\/account)|.\/verify-number' }
